### PR TITLE
Added autocomplete plugin to the cli

### PR DESCRIPTION
**Pull request by ritwizsinha**
image
image
The autocomplete feature works for both commands and flags for now

### CODE REVIEW

**Comment by graywolf336** [comment]
@ritwizsinha how do I test locally? I attempted to but it didn't work..

**Comment by ritwizsinha** [comment]
@graywolf336 you need to run 
```
oclif-example autocomplete [SHELL] 

```
before it is enabled in the shell of your preference [autocomplete](https://github.com/oclif/plugin-autocomplete)

**Comment by ritwizsinha** [comment]
I think this is a problem as the user needs to install autocomplete with the apps cli and run this command. The best solution would be to make this automated.

**Comment by graywolf336** [comment]
@ritwizsinha ah okay, then yeah this isn't an option we can go with. How can we make it part of the CLI itself and be enabled as soon as someone does `npm install -g @rocket.chat/apps-cli`?

**Comment by graywolf336** [comment]
@ritwizsinha any update?

**Comment by ritwizsinha** [comment]
@graywolf336 i am currently working on the hot reload feature for the first phase of GSoC, I'll try getting to it by the next evaluation

**Comment by ritwizsinha** [comment]
@graywolf336 coming back to this feature, here's what I have discovered. The autocomplete feature currently works as follows, when the user installs the cli using npm, the user needs to decide whether to enable the plugin or not  . By running the command 
```rc-apps autocomplete zsh``` 
``` rc-apps autocomplete bash```
depending on the shell being used. This asks the user to add the path for autocomplete scripts to the .bashrc/.zshrc respectively which is needed as autocomplete  is not a feature of the CLI but the shell being used. 
image
After doing this the autocomplete is enabled. For adding this feature here the two possible options :
1. Allow user the freedom to add the autocomplete on his own using the method described above and add this to the readme
2. Add a hook when the CLI is starting for the first time, this checks if the autocomplete directory exists in the ```~/.cache``` dir and if not then it adds the directory by running the autocomplete command in code and adds the path to bash. 
The second method just adds the configuration needed without any need for asking the user although it seems a hack to me

**Comment by graywolf336** [comment]
Let's do a combination of the two, of sorts. Whenever they first run it, we notify them of the ability to autocomplete and how to do it. That way on first run they're presented with the information on how to set it up. In addition to that, we update the documentation with it being highly recommended.

**Pull request merged**
